### ISSUE TITLE
User story: As a user, I should be able to keep the scroll position stays in place instead of jumping back up to the top when changing filters on pages.

### ISSUE THREAD

**Issue by GuanSuns** [TimCoding/HomeSweHome#102]
Currently, when I change filters, the scroll position will jump back up to the top.

**Comment by dav-s** [comment]
We have discussed this. This is semi-intentional. When you put in a new filter query, new results appear. So it is natural to go to the top of the page.

**Comment by dav-s** [comment]
We actually ended up implementing a fix for this in  5b35938.

**Comment by GuanSuns** [comment]
good job
