### ISSUE TITLE
User story: As a user, I would like to see more brief and better-organized descriptions of the dogs. 

### ISSUE THREAD

**Issue by GuanSuns** [TimCoding/HomeSweHome#105]
For example, the description for dog Scorsese is too long and all the words are in one passage (http://homeswehome.me/dog/40536542/).

**Comment by TimCoding** [comment]
Hello, because of your great input, we now have better organized descriptions for dogs. If the description is too long, we truncated the description to 150 words. You can see or hide the remaining words in the description by using the Read More/Read Less button.

**Comment by TimCoding** [comment]
Strong work Timothy

**Comment by TimCoding** [comment]
Thanks Timothy

**Comment by TimCoding** [comment]
You need friends Timothy...
