### ISSUE TITLE
User story: As a user, I would like to see the links to the official website of the development tools on the About page. 

### ISSUE THREAD

**Issue by GuanSuns** [TimCoding/HomeSweHome#107]
Sometimes, I want to learn about some new tools and see if we can use them in our websites.

**Comment by dav-s** [comment]
Added in 22d3bdc. Icons added as well.

**Comment by TimCoding** [comment]
We added links! Now you can learn about all the tools!

**Comment by GuanSuns** [comment]
I see that. Good job
