### ISSUE TITLE
Create helper functions to pull data from CalorieKillerClub API

### ISSUE THREAD

**Issue by TimCoding** [TimCoding/HomeSweHome#117]

**Comment by dav-s** [comment]
Here are their endpoints:

 - `http://api.caloriekiller.club/foods`
 - `http://api.caloriekiller.club/workouts`
 - `http://api.caloriekiller.club/gyms`
 - `http://api.caloriekiller.club/stores`

**Comment by TimCoding** [comment]
Resolved they did a good job of fixing their website
