### ISSUE TITLE
Users will be able to make queries to our API in order to retrieve information about parks.

### ISSUE THREAD

**Issue by TimCoding** [TimCoding/HomeSweHome#65]
Estimate: 2 days

Assumption for Initial Estimate: 
- We already have a good knowledge of Python so creating this portion of the API will not be difficult
- Users will query for specific park directly or they will search for parks pertaining to a certain dog or shelter. This relation already exists in our database. 
-Time will need to be spent testing the API 

Refined Estimate: 4 Days

Actual Time: 5 Days

**Comment by TimCoding** [comment]
We should make sure that if a park being queried does not exist, we error out safely

**Comment by gmac220** [comment]
We need to validate the JSON our API returns and ensure that it is correct and formatted the way we want.

**Comment by rebekkahkoo** [comment]
It is okay for parks to be associated with multiple dogs and shelters
