### ISSUE TITLE
Users can see actual adoption policies and the mission for shelters.

### ISSUE THREAD

**Issue by gmac220** [TimCoding/HomeSweHome#67]
Initial Estimate: 2 days

Assumptions of Initial Estimate: 
- The component for displaying adoption policies and missions can be quickly created in React
- They will be collected from an API that is not owned by us, we assume the API will continue to work
- It does not take a long time to pull from the API for each request

Refined Estimate: 3 days

Actual Time: 2.5 days

**Comment by ewk298** [comment]
The review component may be used in the park and shelter details page. We should make it reusable.

**Comment by rebekkahkoo** [comment]
The review component may require additional CSS in order to position it correctly on the details page

**Comment by gmac220** [comment]
We need to fix the issue of the adoption policy and mission showing HTML tags
