### ISSUE TITLE
Users will be able to make queries to our API in order to retrieve information about dogs.

### ISSUE THREAD

**Issue by gmac220** [TimCoding/HomeSweHome#68]
Estimate: 2 days

Assumptions of Initial Estimate:
- We are assuming that users will make queries for specific dogs or dogs associated with a particular park or shelter
- User only wants response in JSON 
- Team members know Python well so we are confident this task should not take too long

Refined Estimate: 4 Days

Actual Time: 5 Days

**Comment by gmac220** [comment]
We need to make sure that the dogs we select to display and store in our database have shelters associated with them.

**Comment by rebekkahkoo** [comment]
We need make sure this portion of the API has good error handling as well. If a dog does not exist, it should not cause the whole application to crash

**Comment by ewk298** [comment]
Be sure to validate the JSON the API is returning to make sure it is correct. This will require time to test
