### ISSUE TITLE
Description: Users can see actual pictures of the parks they want to visit.

### ISSUE THREAD

**Issue by gmac220** [TimCoding/HomeSweHome#69]
Initial Estimate: 3 Days

Assumption for Initial Estimate: 
- Converting the parks detail pages to React will only take 1-2 days
- Images will only be placed in the detail page's Jumbotron, so we will only need one image per park
- The HomeSweHome API for parks will be complete before starting this story

Refined Estimate: 3.5 Days

Actual Time: 3 Days

**Comment by ewk298** [comment]
We can just use React/CSS in order to resize the images to fit the jumbotron

**Comment by ewk298** [comment]
SOMEBODY ONCE TOLD ME

**Comment by TimCoding** [comment]
THE WORLD IS GUNNA ROLL ME

**Comment by ewk298** [comment]
I AINT THE SHARPEST TOOL IN THE SHEDDDD

**Comment by gmac220** [comment]
SHE WAS LOOKING KINDA DUMB

**Comment by rebekkahkoo** [comment]
WITH HER FINGER AND HER THUMB

**Comment by TimCoding** [comment]
IN THE SHAPE OF AN "L" ON HER FOREHEAD

**Comment by dav-s** [comment]
WELL

**Comment by ewk298** [comment]
THE YEARS START COMIN AND THEY DONT STOP COMING

**Comment by ewk298** [comment]
In case resizing the images distorts the images, we can try to find images that are already the size we want

**Comment by dav-s** [comment]
Davis: "Incase resizing the images distorts the images, we can try to find images that are already the size we want"

**Comment by TimCoding** [comment]
Rebekkah: "Good one Davis"

**Comment by TimCoding** [comment]
Wouldn't you agree
