### ISSUE TITLE
Users will be able to see the text that they searched for highlighted on the results page.

### ISSUE THREAD

**Issue by TimCoding** [TimCoding/HomeSweHome#88]
Estimate: 2 Days 

Assumptions for Initial Estimate: 

Refined Estimate: 

Actual Time:

**Comment by TimCoding** [comment]
I think in class they recommended that we use Mark.js. Have we considered implementing our own version of highlighting text?

**Comment by ewk298** [comment]
Nah let's use React-highlight-words. A previous year's project used it
