### ISSUE TITLE
Users will be able to hover over the information cards in order to get basic info about a particular instance.

### ISSUE THREAD

**Issue by TimCoding** [TimCoding/HomeSweHome#89]
Estimate:

Assumptions for Initial Estimate: 

Refined Estimate: 

Actual Time:

**Comment by TimCoding** [comment]
This seems pretty straight forward, let's just make sure to handle any overflow properly.

**Comment by rebekkahkoo** [comment]
Since the hover text is embedded in the card itself, setting the overflow to scroll would reposition the image, so I just used hidden
