### ISSUE TITLE
Users will be able to filter dogs, parks, and shelters based on certain characteristics.

### ISSUE THREAD

**Issue by TimCoding** [TimCoding/HomeSweHome#90]
Estimate: 4 Days

Assumptions for Initial Estimate: 
- This feature will require extra functionality to be added to our API. There is too much data to perform filtering on the frontend. 
- We will need to add something to the UI so users can select how they want to filter.

Refined Estimate: 4 Days 

Actual Time: 4 Days

**Comment by TimCoding** [comment]
Let's make sure to write Postman tests for the new API endpoints.

**Comment by rebekkahkoo** [comment]
what characteristics should we filter by for each model?

**Comment by ewk298** [comment]
Parks
- star rating

Dogs
- Breed
- HouseTrained
- Friendly

Shelter
- City
