### ISSUE TITLE
Users will be able to search for a particular dog, park, or shelter that they want.

### ISSUE THREAD

**Issue by TimCoding** [TimCoding/HomeSweHome#91]
Estimate:

Assumptions for Initial Estimate: 

Refined Estimate: 

Actual Time:

**Comment by TimCoding** [comment]
The API call for searching might take a bit to return results. Lets add a spinner to let the user know that we are attempting to get the information they requested.

**Comment by rebekkahkoo** [comment]
let's make the spinner a paw
