### ISSUE TITLE
The dog details page will allow the user to see the name, breed, gender, and age, images, and description of a selected dog.

### ISSUE THREAD

**Issue by TimCoding** [TimCoding/HomeSweHome#97]
Estimated Time: 2 Days

Assumptions: 
-If we give all the details page the same design, then we can reuse the templates and save a lot of time
-We will need to scrap the data 
-We need to learn bootstrap

Adjusted Time: 3 Days

Actual Time: 3 Days

**Comment by ewk298** [comment]
What is bootstrap

**Comment by TimCoding** [comment]
I don't think the details page can all share the same design, some of them will have maps while some won't.

**Comment by dav-s** [comment]
The current pages now display this updated information. We do not have gender or age, however.

**Comment by rebekkahkoo** [comment]
it's okay life goes on
