### ISSUE TITLE
User Story: As a user, I would expect a better quality of the photos.

### ISSUE THREAD

**Issue by GuanSuns** [TimCoding/HomeSweHome#98]
Some of the photos, particularly on the shelters page, are stretched out and hard to see. 
One example is the "Border Collie Rescue (http://homeswehome.me/shelter/TX1980/) & Rehab of Texas (http://homeswehome.me/shelter/TX1980/)" shelter

**Comment by dav-s** [comment]
I think fixed in 51f831

**Comment by GuanSuns** [comment]
good job
