### ISSUE TITLE
User story: As a user, I would like to see images of all the parks. 

### ISSUE THREAD

**Issue by GuanSuns** [TimCoding/HomeSweHome#99]
Beckert Park and Les Lacs Trail have images that don't show the park. It would be nice to see a picture of the grass, open field, scenery

**Comment by GuanSuns** [comment]
![screen shot 2018-04-11 at 11 52 41 pm](https://user-images.githubusercontent.com/18614719/38656975-74dd468e-3de3-11e8-814e-1f4501507669.png)

**Comment by dav-s** [comment]
Good suggestion. We have discussed that this is out of the scope of our project. Unfortunately, we do not have the resources to curate these images (via hand selection or classification). This is more of a problem with curation of images on Yelp.

**Comment by GuanSuns** [comment]
good job
